// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package openskynetwork

import (
	"context"
	"encoding/json/v2"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "API"

var defaultBaseURL = &url.URL{
	Scheme: "https",
	Host:   "opensky-network.org",
	Path:   "/api",
}

// Client is an HTTP client for the openskynetwork API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	for _, opt := range opts {
		opt(c)
	}

	return c, nil
}

// All State Vectors
//
//	GET /states/all
func (c *Client) ListAllStateVectors(ctx context.Context, params *ListAllStateVectorsParams) (*CurrentStates, error) {
	return c.ListAllStateVectorsWithResult[CurrentStates](ctx, params)
}

// All State Vectors
// You can define a custom result to unmarshal the response into.
//
//	GET /states/all
func (c *Client) ListAllStateVectorsWithResult[R any](ctx context.Context, params *ListAllStateVectorsParams) (*R, error) {
	u := c.baseURL.JoinPath("states", "all")
	if params != nil {
		q := make(url.Values, 4)

		if params.Lamax != "" {
			q["lamax"] = []string{params.Lamax}
		}

		if params.Lamin != "" {
			q["lamin"] = []string{params.Lamin}
		}

		if params.Lomax != "" {
			q["lomax"] = []string{params.Lomax}
		}

		if params.Lomin != "" {
			q["lomin"] = []string{params.Lomin}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// GET /flights/all
func (c *Client) ListAllFlights(ctx context.Context, params *ListAllFlightsParams) (Flights, error) {
	out, err := c.ListAllFlightsWithResult[Flights](ctx, params)
	if err != nil {
		return nil, err
	}

	return *out, nil
}

// GET /flights/all
func (c *Client) ListAllFlightsWithResult[R any](ctx context.Context, params *ListAllFlightsParams) (*R, error) {
	u := c.baseURL.JoinPath("flights", "all")
	if params != nil {
		q := make(url.Values, 2)

		if !params.Begin.IsZero() {
			q["begin"] = []string{strconv.Itoa(int(params.Begin.Unix()))}
		}

		if !params.End.IsZero() {
			q["end"] = []string{strconv.Itoa(int(params.End.Unix()))}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	case http.StatusForbidden:
		// Forbidden
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "text/plain":
			out, err := io.ReadAll(rsp.Body)
			if err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return nil, api.NewErrBody(rsp, out)
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Flights by Aircraft
//
//	GET /flights/aircraft
func (c *Client) ListFlightsByAircraft(ctx context.Context, params *ListFlightsByAircraftParams) (Flights, error) {
	out, err := c.ListFlightsByAircraftWithResult[Flights](ctx, params)
	if err != nil {
		return nil, err
	}

	return *out, nil
}

// Flights by Aircraft
// You can define a custom result to unmarshal the response into.
//
//	GET /flights/aircraft
func (c *Client) ListFlightsByAircraftWithResult[R any](ctx context.Context, params *ListFlightsByAircraftParams) (*R, error) {
	u := c.baseURL.JoinPath("flights", "aircraft")
	if params != nil {
		q := make(url.Values, 3)

		if !params.Begin.IsZero() {
			q["begin"] = []string{strconv.Itoa(int(params.Begin.Unix()))}
		}

		if !params.End.IsZero() {
			q["end"] = []string{strconv.Itoa(int(params.End.Unix()))}
		}

		if params.Icao24 != "" {
			q["icao24"] = []string{string(params.Icao24)}
		}

		u.RawQuery = q.Encode()
	}

	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
