// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package openskynetwork

import (
	"encoding/json/jsontext"
	"encoding/json/v2"
	"fmt"
	"time"

	"github.com/MarkRosemaker/jsonutil"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
	json.WithMarshalers(json.JoinMarshalers(
		json.MarshalToFunc(jsonutil.TimeMarshalIntUnix),
	)),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(jsonutil.TimeUnmarshalIntUnix),
	)),
)

// ListAllStateVectorsParams holds the query parameters for ListAllStateVectors.
type ListAllStateVectorsParams struct {
	Lamax string
	Lamin string
	Lomax string
	Lomin string
}

// CurrentStates defines a model
type CurrentStates struct {
	Time   time.Time `json:"time"`
	States States    `json:"states"`
}

// State defines a model
type State struct {
	// Unique ICAO 24-bit address of the transponder in hex string representation.
	ICAO24 string
	// Callsign of the vehicle (8 chars). Can be null if no callsign has been received.
	Callsign string
	// Country name inferred from the ICAO 24-bit address.
	OriginCountry string
	// Unix timestamp (seconds) for the last position update. Can be null if no position report was received by OpenSky within the past 15s.
	TimePosition time.Time
	// Unix timestamp (seconds) for the last update in general. This field is updated for any new, valid message received from the transponder.
	LastContact time.Time
	// WGS-84 longitude in decimal degrees. Can be null.
	Longitude float64
	// WGS-84 latitude in decimal degrees. Can be null.
	Latitude float64
	// Barometric altitude in meters. Can be null.
	BaroAltitude float64
	// Boolean value which indicates if the position was retrieved from a surface position report.
	OnGround bool
	// Velocity over ground in m/s. Can be null.
	Velocity float64
	// True track in decimal degrees clockwise from north (north=0°). Can be null.
	TrueTrack float64
	// Vertical rate in m/s. A positive value indicates that the airplane is climbing, a negative value indicates that it descends. Can be null.
	VerticalRate float64
	// IDs of the receivers which contributed to this state vector. Is null if no filtering for sensor was used in the request.
	Sensors        struct{}
	GeoAltitude    float64
	Squawk         string
	SPI            bool
	PositionSource int
}

func (a *State) Items(yield func(int, any) bool) {
	for i, v := range []any{&a.ICAO24, &a.Callsign, &a.OriginCountry, &a.TimePosition, &a.LastContact, &a.Longitude, &a.Latitude, &a.BaroAltitude, &a.OnGround, &a.Velocity, &a.TrueTrack, &a.VerticalRate, &a.Sensors, &a.GeoAltitude, &a.Squawk, &a.SPI, &a.PositionSource} {
		if !yield(i, v) {
			return
		}
	}
}

// UnmarshalJSONFrom implements [json.UnmarshalerFrom].
func (a *State) UnmarshalJSONFrom(dec *jsontext.Decoder) error {
	if k := dec.PeekKind(); k != jsontext.KindBeginArray {
		return &json.SemanticError{JSONKind: k}
	}

	if _, err := dec.ReadToken(); err != nil {
		return err
	}

	for _, f := range a.Items {
		if dec.PeekKind() == jsontext.KindEndArray {
			return &json.SemanticError{Err: fmt.Errorf("array shorter than 17")}
		}

		if err := json.UnmarshalDecode(dec, f); err != nil {
			return err
		}
	}

	if k := dec.PeekKind(); k != jsontext.KindEndArray {
		return &json.SemanticError{JSONKind: k, Err: fmt.Errorf("array longer than 17")}
	}

	_, err := dec.ReadToken()
	return err
}

// MarshalJSONTo implements [json.MarshalerTo].
func (a State) MarshalJSONTo(enc *jsontext.Encoder) error {
	if err := enc.WriteToken(jsontext.BeginArray); err != nil {
		return err
	}

	for _, v := range a.Items {
		if err := json.MarshalEncode(enc, v); err != nil {
			return err
		}
	}

	if err := enc.WriteToken(jsontext.EndArray); err != nil {
		return err
	}

	return nil
}

// States defines a model
type States []State
